### ISSUE TITLE
Setting a basename is not working

### ISSUE THREAD

**Issue by georgekaran** [Lomray-Software/vite-ssr-boost#17]
**Describe the bug**
We want to serve our project in sub-path, but as we tried to use the `basename` property from React Router + `base` from Vite we're getting a not found page.

**To Reproduce**
1. Modify `vite.config.ts` to have a base, example, base: '/foo/';
2. Add to the `client.ts` the same value under the `routerOptions` object.
3. Build the application
4. Start the application using `npm run start:ssr`
5. Access the application using `localhost:3000/foo`
6. A not found page is now displayed.

**Expected behavior**
It should be possible to access the pages using a sub-path.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 15.1.0
 - Browser Chrome
 - Version 123

**Additional context**

**Comment by MatthewPattell** [comment]
Hi @georgekaran thank you for reporting. 
1. Install latest version of vite-ssr-boost
2. Follow [this instructions](https://github.com/Lomray-Software/vite-ssr-boost?tab=readme-ov-file#change-basename)

**Comment by Fryuni** [comment]
Hey @MatthewPattell 👋🏼

I work with @georgekaran, thanks for the quick response.

We identified and worked around two problems that prevented this behavior for us. The changes from https://github.com/Lomray-Software/vite-ssr-boost/commit/792499e2597c79a7d1bc310ca22b6f2168befbc8 fix one of them. The other is the serving the Vite-generated assets in that same sub-path.

Vite has a `base` option that makes it emit the reference to all assets assuming that they will be served from that path, setting that to `/foo`, for example, emits imports to `/foo/chunks/...` instead of `/chunks/...`.
But the middleware serving the static assets is not taking that into account and serves them on the root, so `/foo/chunks/...` leads to a 404 page.

Our workaround was to disable the static middleware and wire it manually on the base path from `onServerCreated`.

**Comment by MatthewPattell** [comment]
Hi @Fryuni 
Thank you for reporting. Install latest version and please, [check it out](https://github.com/Lomray-Software/vite-ssr-boost?tab=readme-ov-file#change-base-for-static-assets)

**Comment by Fryuni** [comment]
Awesome, we'll try it out and report back. Thanks again for the fast reply!

**Comment by Fryuni** [comment]
All working fine, thanks @MatthewPattell!

Feel free to close this issue. George is OOO, he can close it once he gets back if you prefer
