### ISSUE TITLE
Do we need to use express?

### ISSUE THREAD

**Issue by rjvim** [Lomray-Software/vite-ssr-boost#5]
From dependencies and `onServerCreated` function, it looks like express server instance is being passed. Just want to make sure if we pass anything server like fastify, does it work? How to make it work on cloudflare worker?

**Comment by MatthewPattell** [comment]
@rjvim Currently, there is no option to pass or specify what will be used as the server. Right now, it's only Express because everything was initially developed for Docker containerization. 

[ Integration with Fastify](https://github.com/orgs/Lomray-Software/projects/2?pane=issue&itemId=46215934) is planned in the near future.

I don't think Fastify will help if the goal is to deploy ssr-boost in SSR mode (only SPA will support) on Cloudflare Workers, [judging by the comments](https://community.cloudflare.com/t/how-to-deploy-nodejs-express-app-to-workers/233925).

However, there are no problems with deploy on [AWS Amplify, Vercel or Docker](https://github.com/Lomray-Software/vite-template?tab=readme-ov-file#aws-amplify-build-amplifyyml---ssr)

**Comment by rjvim** [comment]
I could have been more explicit. Those are independent questions.

- Does it support fastify (You have answered that, thanks)
- How to make it work on cloudflare workers?

**Comment by rjvim** [comment]
Vike supports CF Workers with Streaming. Hopefully that reference might help if you want to support in future. Here is the link: https://vike.dev/cloudflare-workers

**Comment by MatthewPattell** [comment]
@rjvim Well, with Cloudflare, things are a bit more serious. As with Vercel and AWS Amplify, it won't work the same way here. It's necessary to rebuild the server, for example, eliminate Express. Thanks for the link; I'll add deploying on Cloudflare Worker to the [backlog](https://github.com/orgs/Lomray-Software/projects/2?pane=issue&itemId=46215934).

**Comment by rjvim** [comment]
Closing this issue. 

Take away:

- Fastify Integration is planned
- CF Workers is in backlog
